version: '2'

services:

  #  The Application
  app:
    container_name: crawl_nct
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    command: php-fpm
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    restart: always

  # The Web Server
  web:
    container_name: nginx_server
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    command: nginx -g "daemon off;"
    restart: always
    ports:
      - 8990:80

  # The Database
  database:
    container_name: mysql_database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=nct"
      - "MYSQL_USER=phpmyadmin"
      - "MYSQL_PASSWORD=phpmyadmin"
      - "MYSQL_ROOT_PASSWORD=root."
    restart: always
    ports:
      - 8991:3306

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
       - "PMA_ARBITRARY=1"
       - "PMA_HOST=mysql_database"
       - "PMA_PORT=3306"
       - "PMA_USER=phpmyadmin"
       - "PMA_PASSWORD=phpmyadmin"
      restart: always
      ports:
       - 8992:80

volumes:
  dbdata: